version: '3.7'  
services:
  message.queue:
    image: rabbitmq:3
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    build:
      context: .
    depends_on:
      message.queue:
        condition: service_healthy
    environment:
      - MQ_URL=message.queue
      - MQ_USER=guest
      - MQ_PASS=guest
      - MQ_PORT=5672
    ports:
      - "8000:80"